import os
from flask import Flask, request
from login import NYCCitiBikeParser
import json

app = Flask(__name__)
port = int(os.environ.get('PORT', 5934))   # arbitrarily generated by pressing random buttons

@app.route('/')
def main():
	return app.send_static_file('main.html')


@app.route('/getdata', methods=['POST'])
def get_data():

	username = request.get_json()['username']
	password = request.get_json()['password']
	parser = NYCCitiBikeParser(username, password)
	trips = parser.get_trips()
	return json.dumps(trips)

if __name__ == '__main__':
	app.run(debug=True, port=port)